config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  resources :phrases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #Home routing and it root url
  get 'home', to: 'home#index', as: :home
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/phrase.rb
class Phrase < ApplicationRecord
    def self.get_random_phrase
        #what do we need to do to extract a random quote from our db?
        #The code below also works but relies on SQLite's Random() 
        #function, aka not the greatest code
        #order('Random()').first
        #random().first
        #The more "rails" way to do it:
        #puts self.active.to_a.sample
        self.active.to_a.sample
        #'active' scope called
        #'to_a' executes a query and returns an array of Phrase objects
        # 'sample' is a Ruby method that randomly takes a value from an array (a Phrase in this case)

    end
    #make sure both English and Spanish translations are included
    validates_presence_of :spanish, :translation

    #scopes we can use
    scope :alphabetical, -> { order('translation')}
    scope :active, -> { where(active:true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #get the data we want
    @phrase = Phrase.get_random_phrase
    #send to a view template and layout
    #default to home#index
  end
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  before_action :set_phrase, only: %i[ show edit update destroy ]

  # GET /phrases or /phrases.json
  def index
    @phrases = Phrase.all
    #@phrases = Phrase.active.alphabetical.paginate(:page => params[:page]).per_page(10)
  end

  # GET /phrases/1 or /phrases/1.json
  def show
    
  end

  # GET /phrases/new
  def new
    @phrase = Phrase.new
  end

  # GET /phrases/1/edit
  def edit
  end

  # POST /phrases or /phrases.json
  def create
    @phrase = Phrase.new(phrase_params)

    respond_to do |format|
      if @phrase.save
        format.html { redirect_to phrase_url(@phrase), notice: "Phrase was successfully created." }
        format.json { render :show, status: :created, location: @phrase }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phrases/1 or /phrases/1.json
  def update
    respond_to do |format|
      if @phrase.update(phrase_params)
        format.html { redirect_to phrase_url(@phrase), notice: "Phrase was successfully updated." }
        format.json { render :show, status: :ok, location: @phrase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phrases/1 or /phrases/1.json
  def destroy
    @phrase.destroy

    respond_to do |format|
      format.html { redirect_to phrases_url, notice: "Phrase was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phrase
      @phrase = Phrase.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def phrase_params
      params.require(:phrase).permit(:spanish, :translation, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/views/home/index.html.erb
<p>This simple site to randomly select a phrase from a collection of Spanish phrases <p>
<p class="supertiny">&nbsp;</p>
<h1><%= @phrase.spanish %></h1><br>
<h2><%= @phrase.translation %></h2>

<p>&nbsp;</p>
<p>&nbsp;</p>
<%= link_to 'Add a new Spanish phrase to our set', new_phrase_path %>
<p class="supertiny">&nbsp;</p>
<%= link_to 'See all our phrases here', phrases_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TranslationApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<body>
	  <div id="wrap">
	    <div id="header">

		<%= link_to(image_tag('phrases-phrases-everywhere.jpeg', height: '200'), home_path) %>
	    </div> <!-- end of header div -->
	    <br />

	    <div id="body">
	      <% flash.each do |name, msg| %>
	        <%= content_tag :div, msg, :id => "flash_#{name}" %>
	      <% end %>
	      <%= yield %>
	    
	    </div> <!-- end of body div -->

      <!-- add in a partial that will provide a footer -->
	    <%= render :partial => "partials/footer" %>
	  </div><!-- end of wrap div -->
	</body>
</html>

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<div id="footer">

  <div id="copy">
    Webmaster: <%= mail_to("ggongora@cmu.edu", "Prof. GS", :encode => "javascript") %> 
    &nbsp;&nbsp;&copy 2022
  </div>

</div>

app/views/phrases/_form.html.erb
<%= form_with(model: phrase, local: true) do |form| %>
  <% if phrase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phrase.errors.count, "error") %> prohibited this phrase from being saved:</h2>

      <ul>
      <% phrase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :spanish %>
    <%= form.text_field :spanish %>
  </div>

  <div class="field">
    <%= form.label :translation %>
    <%= form.text_field :translation %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/phrases/edit.html.erb
<h1>Editing Phrase</h1>

<%= render 'form', phrase: @phrase %>

<%= link_to 'Show', @phrase %> |
<%= link_to 'Back', phrases_path %>

app/views/phrases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phrases</h1>

<table>
  <thead>
    <tr>
      <th>Spanish</th>
      <th>Translation</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% for phrase in @phrases%>
    <tr class="<%= cycle('dg_list_line_odd', 'dg_list_line_even') %>">
    <td width="350"><%= link_to phrase.spanish, phrase_path(phrase) %></td>
    <td width="350"><%= phrase.translation %></td>
    <td width="90" align="center">
    <%= link_to(image_tag("icons/edit_dg.gif", :border => 0), edit_phrase_path(phrase))  %>&nbsp;<%= link_to(image_tag("icons/delete_dg.gif", :border => 0), phrase_path(phrase), :confirm => 'Are you sure you wish to delete this information?', :method => :delete) %>
  </td>
  </tr>
<% end %>
</table>
<p class="supertiny"></p>
<!--%= will_paginate @phrases %-->

<%= link_to 'Add a new spanish phrase', new_phrase_path %>

app/views/phrases/new.html.erb
<h1>New Phrase</h1>

<%= render 'form', phrase: @phrase %>

<%= link_to 'Back', phrases_path %>

app/views/phrases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Spanish:</strong>
  <%= @phrase.spanish %>
</p>

<p>
  <strong>Translation:</strong>
  <%= @phrase.translation %>
</p>

<p>
  <strong>Active:</strong>
  <%= @phrase.active %>
</p>

<%= link_to 'Edit', edit_phrase_path(@phrase) %> |
<%= link_to 'Back', phrases_path %>